In [ ]:
                ###DEEP LEARNING Fractal-1 : Assignment-1 

In [1]:
#Step1: Download a CNN model trained on the ImageNet classification dataset

import torch
import torchvision.models as models

# Download pre-trained ResNet50 model
model = models.resnet50(pretrained=True)

# Save the model weights
torch.save(model.state_dict(), 'imagenet_resnet50.pth')


C:\Users\Admin\anaconda3\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
C:\Users\Admin\anaconda3\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


In [ ]:
model

In [2]:
import os
import torch
import torchvision.transforms as transforms
from torchvision.models import resnet50
from torch.utils.data import DataLoader
from torchvision.datasets import ImageFolder
from PIL import Image




In [3]:
model = resnet50(pretrained=True)
model.eval()  # Set the model to evaluation mode

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [ ]:
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.image import load_img, img_to_array



# Define paths to the dataset
data_dir = 'C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007'
jpeg_images_dir = os.path.join(data_dir, 'JPEGImages')
annotations_dir = os.path.join(data_dir, 'Annotations')

# Set image size
img_width, img_height = 224, 224

# List all JPEG image files
jpeg_images_files = os.listdir(jpeg_images_dir)

# Initialize lists to store features and labels
features = []
labels = []

# Loop over each image file
for image_file in jpeg_images_files:
    # Load image
    print(image_file)
    image_path = os.path.join(jpeg_images_dir, image_file)
    img = load_img(image_path, target_size=(img_width, img_height))
    img_array = img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)

    # Preprocess image
    img_array = tf.keras.applications.vgg16.preprocess_input(img_array)
    
    transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Resize images to match the model input size
    transforms.ToTensor(),  # Convert images to tensors
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])  # Normalize images
])


    # Extract features
    features.append(vgg16_model.predict(img_array))
    
    # Extract class label from annotation file
    annotation_file = image_file.split('.')[0] + '.xml'
    annotation_path = os.path.join(annotations_dir, annotation_file)
    # Extract the class label from the annotation file and append it to the labels list
    # You need to implement the code to parse the XML file and extract the class label
    
    labels.append(class_label)  # Replace class_label with the actual class label extracted from the annotation file

# Convert features and labels to NumPy arrays
features = np.vstack(features)
labels = np.array(labels)

# Save the extracted features and labels
features_path = '/path/to/save/features.npy'
np.save(features_path, features)

labels_path = '/path/to/save/labels.npy'
np.save(labels_path, labels)


In [6]:
import os
import tensorflow as tf
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np

# Define the paths to the PASCAL VOC dataset
dataset_path = 'C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007'
annotations_path = os.path.join(dataset_path, 'Annotations')
jpeg_images_path = os.path.join(dataset_path, 'JPEGImages')

# Load pre-trained ResNet50 model
model = tf.keras.applications.ResNet50(weights='imagenet', include_top=False, pooling='avg')

# Function to extract features from images with corresponding annotations
def extract_features_and_labels(image_paths, model):
    features = []  # List to store extracted features
    labels = []    # List to store corresponding labels

    for image_path in image_paths:
        print(image_path)
        img = image.load_img(image_path, target_size=(224, 224))
        img = image.img_to_array(img)
        img = preprocess_input(img)
        img = np.expand_dims(img, axis=0)

        feature = model.predict(img)
        features.append(feature.flatten())
        
        label = os.path.splitext(os.path.basename(image_path))[0]
        print(label)
        labels.append(label)

    features = np.stack(features)
    labels = np.array(labels)
    return features,labels

# Load the annotations and corresponding image filenames
annotations = sorted(os.listdir(annotations_path))
image_filenames = [filename.replace('.xml', '.jpg') for filename in annotations]
image_paths = [os.path.join(jpeg_images_path, filename) for filename in image_filenames]

# Extract features and labels from the dataset
features, labels = extract_features_and_labels(image_paths, model)

# Print the shape of the extracted features and labels
print("Features shape:", features.shape)
print("Labels shape:", labels.shape)

C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000001.jpg
1/1 [==============================] - 2s 2s/step
000001
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000002.jpg
1/1 [==============================] - 0s 212ms/step
000002
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000003.jpg
1/1 [==============================] - 0s 247ms/step
000003
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000004.jpg
1/1 [==============================] - 0s 184ms/step
000004
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000006.jpg
1/1 [==============================] - 0s 232ms/step
000006
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000008.jpg
1/1 [==============================] - 0s 258ms/step
000008
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000010.jpg
1/1 [===============

KeyboardInterrupt: 

In [8]:
import os
import tensorflow as tf
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np
import xml.etree.ElementTree as ET

# Define the paths to the PASCAL VOC dataset
dataset_path = 'C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007'
jpeg_images_path = os.path.join(dataset_path, 'JPEGImages')
annotations_path = os.path.join(dataset_path, 'Annotations')

# Load pre-trained ResNet50 model
model = tf.keras.applications.ResNet50(weights='imagenet', include_top=False, pooling='avg')

# Function to extract features and class labels from images with corresponding annotations
def extract_features_and_labels(image_paths, annotation_paths, model):
    features = []  # List to store extracted features
    class_labels = []  # List to store corresponding class labels

    for image_path, annotation_path in zip(image_paths, annotation_paths):
        print(image_path)
        # Load and preprocess the image
        img = image.load_img(image_path, target_size=(224, 224))
        img = image.img_to_array(img)
        img = preprocess_input(img)
        img = np.expand_dims(img, axis=0)

        # Extract features using the pre-trained model
        feature = model.predict(img)
        features.append(feature.flatten())

        # Extract class label from the annotation file
        tree = ET.parse(annotation_path)
        root = tree.getroot()
        class_label = root.find('object').find('name').text
        print(class_label," classlabel")
        class_labels.append(class_label)

    features = np.stack(features)
    class_labels = np.array(class_labels)
    return features, class_labels

# Load the image and annotation filenames
image_filenames = sorted(os.listdir(jpeg_images_path))
image_paths = [os.path.join(jpeg_images_path, filename) for filename in image_filenames]
annotation_filenames = sorted(os.listdir(annotations_path))
annotation_paths = [os.path.join(annotations_path, filename) for filename in annotation_filenames]

# Extract features and class labels from the dataset
features, class_labels = extract_features_and_labels(image_paths, annotation_paths, model)

# Print the shape of the extracted features and class labels
print("Features shape:", features.shape)
print("Class labels shape:", class_labels.shape)


C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000001.jpg
1/1 [==============================] - 3s 3s/step


AttributeError: 'list' object has no attribute 'find'

In [13]:
import os
import tensorflow as tf
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
import numpy as np
import xml.etree.ElementTree as ET

# Define the paths to the PASCAL VOC dataset
dataset_path = 'C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007'
jpeg_images_path = os.path.join(dataset_path, 'JPEGImages')
annotations_path = os.path.join(dataset_path, 'Annotations')

# Load pre-trained ResNet50 model
model = tf.keras.applications.ResNet50(weights='imagenet', include_top=False, pooling='avg')

# Function to extract features and class labels from images with corresponding annotations
def extract_features_and_labels(image_paths, annotation_paths, model):
    features = []  # List to store extracted features
    class_labels = []  # List to store corresponding class labels

    for image_path, annotation_path in zip(image_paths, annotation_paths):
        # Load and preprocess the image
        print(image_path)
        img = image.load_img(image_path, target_size=(224, 224))
        img = image.img_to_array(img)
        img = preprocess_input(img)
        img = np.expand_dims(img, axis=0)

        # Extract features using the pre-trained model
        feature = model.predict(img)
        features.append(feature.flatten())

        # Extract class labels from the annotation file
        tree = ET.parse(annotation_path)
        root = tree.getroot()
        for obj in root.findall('object'):
            class_label = obj.find('name').text
            print(class_label," classlabel")
            class_labels.append(class_label)

    features = np.stack(features)
    class_labels = np.array(class_labels)
    return features, class_labels

# Load the image and annotation filenames
image_filenames = sorted(os.listdir(jpeg_images_path))
image_paths = [os.path.join(jpeg_images_path, filename) for filename in image_filenames]
annotation_filenames = sorted(os.listdir(annotations_path))
annotation_paths = [os.path.join(annotations_path, filename) for filename in annotation_filenames]

# Extract features and class labels from the dataset
features, class_labels = extract_features_and_labels(image_paths, annotation_paths, model)

# Print the shape of the extracted features and class labels
print("Features shape:", features.shape)
print("Class labels shape:", class_labels.shape)



C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000001.jpg
1/1 [==============================] - 2s 2s/step
dog  classlabel
person  classlabel
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000002.jpg
1/1 [==============================] - 1s 926ms/step
train  classlabel
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000003.jpg
1/1 [==============================] - 1s 903ms/step
sofa  classlabel
chair  classlabel
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000004.jpg
1/1 [==============================] - 1s 919ms/step
car  classlabel
car  classlabel
car  classlabel
car  classlabel
car  classlabel
car  classlabel
car  classlabel
C:/Users/Admin/M22AI608-DeepLearning-Assignment1/VOCdevkit/VOC2007\JPEGImages\000006.jpg
1/1 [==============================] - 1s 924ms/step
pottedplant  classlabel
diningtable  classlabel
chair  classlabel
chair  classlabel
chair  cl

In [37]:
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import StandardScaler

# Perform label binarization
label_binarizer = LabelBinarizer()
labels_binary = label_binarizer.fit_transform(class_labels)

# Normalize the features
scaler = StandardScaler()
normalized_features = scaler.fit_transform(features)


In [41]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.utils import shuffle

# Extract features and class labels from the dataset
print(features, class_labels )

# Convert class labels to numerical format
label_encoder = LabelEncoder()
class_labels_encoded = label_encoder.fit_transform(class_labels)

# Normalize the features
scaler = StandardScaler()
normalized_features = scaler.fit_transform(features)

# Check if the number of samples is consistent
if len(class_labels_encoded) != len(normalized_features):
    # Shuffle and align the arrays
    normalized_features, class_labels_encoded = shuffle(normalized_features, class_labels_encoded, random_state=42)

# Assign the aligned arrays to the final variables
class_labels_aligned = class_labels_encoded
features_aligned = normalized_features


[[0.07647985 0.25056505 0.         ... 0.         0.18714465 0.16677545]
 [0.10368208 0.5432831  0.23987362 ... 0.04330365 0.19134237 0.19945195]
 [0.38128242 0.09368706 0.02202212 ... 0.04409217 0.1156241  0.42023447]
 ...
 [0.6847967  1.1777755  0.23117045 ... 1.322935   1.157848   0.2290475 ]
 [0.04936857 0.34053943 0.16784397 ... 0.21982077 0.48850164 0.46428603]
 [0.07060013 1.0090587  0.36555517 ... 0.13180257 0.48678395 1.2323241 ]] ['dog' 'person' 'train' ... 'person' 'diningtable' 'car']


ValueError: Found input variables with inconsistent numbers of samples: [4952, 14976]

In [43]:
#Converting features and labels to numpy arrays
import numpy as np

# Convert features_aligned and class_labels_aligned to NumPy arrays
#features_array = np.array(features)
#class_labels_array = np.array(class_labels)

# Print the shape of the converted arrays
#print("Features shape:", features_array.shape)
#print("Class labels shape:", class_labels_array.shape)


Features shape: (4952, 2048)
Class labels shape: (14976,)


In [58]:
##Converting features and labels to numpy arrays
import numpy as np

# Determine the minimum size of the arrays
min_size = min(features.shape[0], class_labels.shape[0])

# Subset the arrays to the minimum size
features_aligned = features[:min_size]
class_labels_aligned = class_labels[:min_size]

# Print the shape of the aligned arrays
print("Features shape:", features_aligned.shape)
print("Class labels shape:", class_labels_aligned.shape)


Features shape: (4952, 2048)
Class labels shape: (4952,)


In [51]:
#perform multi-label binarization on labels
from sklearn.preprocessing import LabelBinarizer

# Create an instance of LabelBinarizer
binarizer = LabelBinarizer()

# Perform multi-label binarization
labels_binary = binarizer.fit_transform(class_labels_aligned)

# Print the shape of the binarized labels
print("Binarized labels shape:", labels_binary.shape)


Binarized labels shape: (4952, 20)


In [52]:
#Split data into train and valdiation sets
from sklearn.model_selection import train_test_split

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(features_aligned, labels_binary, test_size=0.2, random_state=42)

# Print the shapes of the training and validation sets
print("Training set shape:", X_train.shape, y_train.shape)
print("Validation set shape:", X_val.shape, y_val.shape)


Training set shape: (3961, 2048) (3961, 20)
Validation set shape: (991, 2048) (991, 20)


In [54]:
# train binary SVM classifiers for each class
from sklearn.svm import SVC
import joblib

# Train binary SVM classifiers
classifiers = []
for i in range(y_train.shape[1]):
    # Prepare the training data for the current class
    y_train_class = y_train[:, i]

    # Create an SVM classifier
    svm = SVC(kernel='linear')

    # Train the SVM classifier
    svm.fit(X_train, y_train_class)

    # Append the trained classifier to the list
    classifiers.append(svm)

    # Save the trained classifier
    joblib.dump(svm, f'classifier_{i}.joblib')


In [56]:
#evaluate the classification accuracy for all the 20 classes on the validation set. Also provide the confusion matrix.

from sklearn.metrics import accuracy_score, confusion_matrix

# Load the saved SVM classifiers
classifiers = []
for i in range(labels_binary.shape[1]):
    svm = joblib.load(f'classifier_{i}.joblib')
    classifiers.append(svm)

# Predict class labels for the validation set
predicted_labels = []
for svm in classifiers:
    predicted_label = svm.predict(X_val)
    predicted_labels.append(predicted_label)

# Convert the predicted labels to a numpy array
predicted_labels = np.array(predicted_labels).T

# Calculate the overall accuracy
overall_accuracy = accuracy_score(y_val, predicted_labels)
print("Overall Accuracy:", overall_accuracy)

# Calculate the accuracy for each class
class_accuracies = []
for i in range(labels_binary.shape[1]):
    class_accuracy = accuracy_score(y_val[:, i], predicted_labels[:, i])
    class_accuracies.append(class_accuracy)

# Print the accuracy for each class
for i, class_accuracy in enumerate(class_accuracies):
    class_name = label_binarizer.classes_[i]
    print(f"Accuracy for class {class_name}: {class_accuracy}")

# Generate the confusion matrix
confusion_mat = confusion_matrix(y_val.ravel(), predicted_labels.ravel())
print("Confusion Matrix:")
print(confusion_mat)


Overall Accuracy: 0.08375378405650857
Accuracy for class aeroplane: 0.9616548940464178
Accuracy for class bicycle: 0.9525731584258325
Accuracy for class bird: 0.9152371342078708
Accuracy for class boat: 0.9424823410696267
Accuracy for class bottle: 0.900100908173562
Accuracy for class bus: 0.9727547931382442
Accuracy for class car: 0.8012108980827447
Accuracy for class cat: 0.9535822401614531
Accuracy for class chair: 0.7870837537840565
Accuracy for class cow: 0.9566094853683148
Accuracy for class diningtable: 0.9656912209889001
Accuracy for class dog: 0.9132189707366297
Accuracy for class horse: 0.9495459132189707
Accuracy for class motorbike: 0.9495459132189707
Accuracy for class person: 0.5317860746720484
Accuracy for class pottedplant: 0.9212916246215943
Accuracy for class sheep: 0.9656912209889001
Accuracy for class sofa: 0.9465186680121089
Accuracy for class train: 0.970736629667003
Accuracy for class tvmonitor: 0.9656912209889001
Confusion Matrix:
[[17884   945]
 [  816   175]]


In [60]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# Split the data into training and validation sets
X_train, X_val, y_train, y_val = train_test_split(normalized_features, labels_binary, test_size=0.2, random_state=42)

# Train binary SVM classifiers for each class
classifiers = []
for i in range(labels_binary.shape[1]):
    # Prepare the training data for the current class
    y_train_class = y_train[:, i]

    # Create an SVM classifier
    svm = SVC(kernel='linear')

    # Train the SVM classifier
    svm.fit(X_train, y_train_class)

    # Save the trained classifier
    classifiers.append(svm)

# Evaluate the classifiers on the validation set
predictions = []
for i, svm in enumerate(classifiers):
    # Prepare the validation data for the current class
    y_val_class = y_val[:, i]

    # Evaluate the SVM classifier on the validation data
    y_pred = svm.predict(X_val)
    predictions.append(y_pred)

    # Calculate classification metrics for the class
    class_name = label_binarizer.classes_[i]
    print(f"Classification Report for class {class_name}:")
    print(classification_report(y_val_class, y_pred))

# Calculate and print the confusion matrix
confusion_mat = confusion_matrix(y_val.ravel(), np.hstack(predictions))
print("Confusion Matrix:")
print(confusion_mat)
#[[TN  FP]
#[FN  TP]]

Classification Report for class aeroplane:
              precision    recall  f1-score   support

           0       0.98      0.98      0.98       975
           1       0.00      0.00      0.00        16

    accuracy                           0.97       991
   macro avg       0.49      0.49      0.49       991
weighted avg       0.97      0.97      0.97       991

Classification Report for class bicycle:
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       966
           1       0.00      0.00      0.00        25

    accuracy                           0.95       991
   macro avg       0.49      0.49      0.49       991
weighted avg       0.95      0.95      0.95       991

Classification Report for class bird:
              precision    recall  f1-score   support

           0       0.97      0.94      0.96       962
           1       0.00      0.00      0.00        29

    accuracy                           0.91       991
   mac